apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: project-hsiaoairplane-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: project-hsiaoairplane-role
subjects:
- kind: ServiceAccount
  name: project-hsiaoairplane
