apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: clone-role-rolebindings
spec:
  rules:
    - name: clone-role-rolebindings
      match:
        resources:
          kinds:
            - Namespace
          selector:
            matchLabels:
              project: hsiaoairplane
      generate:
        namespace: "{{request.object.metadata.name}}"
        synchronize: true
        cloneList:
          namespace: hsiaoairplane
          kinds:
            - rbac.authorization.k8s.io/v1/Role
            - rbac.authorization.k8s.io/v1/RoleBinding
          selector:
            matchLabels:
              product-rbac: "true"
