apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: project-hsiaoairplane-role
  namespace: hsiaoairplane
  labels:
    product-rbac: "true"
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "watch", "list"]
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "watch", "list"]
