apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: project-hsiaoairplane-role
  namespace: hsiaoairplane
  labels:
    distribute-product-rbac: "true"
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["create", "delete", "get", "list", "patch", "update", "watch"]
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "watch", "list"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "watch", "list"]
