apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: project-airplanehsiao-rolebinding
  namespace: airplanehsiao
  labels:
    distribute-product-rbac: "true"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: project-airplanehsiao-role
subjects:
- kind: ServiceAccount
  name: project-airplanehsiao
  namespace: airplanehsiao
