apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: project-airplanehsiao-role
  namespace: airplanehsiao
  labels:
    distribute-product-rbac: "true"
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "watch", "list"]
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "watch", "list"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "watch", "list"]
