name: Validate Kubernetes YAML with Server-Side Dry Run

on:
  pull_request:
    paths:
      - '**/*.yaml'
      - '**/*.yml'
  push:
    branches:
      - main
    paths:
      - '**/*.yaml'
      - '**/*.yml'

jobs:
  validate-yaml:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
      matrix:
        k8s:
          - v1.19.16
          - v1.20.15
          - v1.21.12
          - v1.22.15
          - v1.23.13
          - v1.24.12
          - v1.25.8
          - v1.26.3
          - v1.27.0
          - v1.28.9
          - v1.29.4
          - v1.30.0
          - v1.31.0
          - v1.32.0
          
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up KIND cluster
      uses: engineerd/setup-kind@v0.5.0
      with:
        version: "v0.14.0"
        image: "kindest/node:${{ matrix.k8s }}"

    - name: Install kubectl
      run: |
        curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
        chmod +x kubectl
        sudo mv kubectl /usr/local/bin/

    - name: Validate YAML files with server-side dry-run
      env:
        KUBECONFIG: /dev/null  # Prevents kubectl from looking for a local kubeconfig
      run: |
        # Find all YAML files
        for file in $(find . -name '*.yaml' -o -name '*.yml'); do
          echo "Validating $file with server-side dry-run..."
          kubectl apply --dry-run=server --server-side -f $file || exit 1
        done
