name: Validate Kubernetes YAML with Server-Side Dry Run

on:
  pull_request:
    paths:
      - '**/*.yaml'
      - '**/*.yml'
  push:
    branches:
      - main
    paths:
      - '**/*.yaml'
      - '**/*.yml'

jobs:
  validate-yaml:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install kubectl
      run: |
        curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
        chmod +x kubectl
        sudo mv kubectl /usr/local/bin/

    - name: Validate YAML files with server-side dry-run
      env:
        KUBECONFIG: /dev/null  # Prevents kubectl from looking for a local kubeconfig
      run: |
        # Find all YAML files
        for file in $(find . -name '*.yaml' -o -name '*.yml'); do
          echo "Validating $file with server-side dry-run..."
          kubectl apply --dry-run=server --server-side -f $file || exit 1
        done
